### ISSUE TITLE
Give users the option to only share audio from a tab

### ISSUE THREAD

**Issue by ArsalaBangash** [grey-software/toonin#177]
The current share screen option doesn't allow a user to only share audio from their tab.

**Comment by alir128** [comment]
"Failed to execute 'getDisplayMedia' on 'MediaDevices': Audio only requests are not supported" not supported by the Api. With the chrome extension it was possible only because we used https://developer.chrome.com/extensions/tabCapture but this is only available from a chrome extension. An option could be to have a toggle that disables sending the video stream to peers after it has been captured. This can work because we can just stop sending the track over RTC.

**Comment by ArsalaBangash** [comment]
I think our best bet would be to create checkboxes for video and audio, and follow your suggestion where we only send selected tracks over WebRTC.
