### ISSUE TITLE
No check on server if room exists or not.

### ISSUE THREAD

**Issue by alir128** [grey-software/toonin#47]

**Comment by Lakshya2610** [comment]
This has been fixed in pull request #51

**Comment by Lakshya2610** [comment]
@alir128 The reason I re-open this issue is we still don't have a system to check if the src for a room still exists. In the event that user doesn't stop streaming and closes chrome directly, server won't know if the user is still active, even though the room is now inaccessible. Ideally, we should have some sort of ping system to check the status of the room every minute or so

**Comment by alir128** [comment]
![image](https://user-images.githubusercontent.com/22705846/67629505-234e1200-f84d-11e9-9b7b-fe84cc75f9c0.png)

**Comment by alir128** [comment]
the functionality already exists since last week, the tabs.onRemoved listener checks once the streaming tab is existed it makes disconnect room call and all clients automatically switch back the state where they can connect to another or host a room.

**Comment by Lakshya2610** [comment]
what if the user closes the window itself instead of just the tab? Maybe we can add a onclose handler?

**Comment by alir128** [comment]
I just tested the scenario also (1 tab only on a window which is the host) and connected a client. I exited the host (window not tab) and the clients still received the host logoff message from the server and got reset. So I think the tab listener also works as a window close listener also.
